# Generated by Django 5.2.6 on 2025-09-05 21:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام دسته')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('color', models.CharField(default='#007bff', help_text='رنگ دسته (کد هگز)', max_length=7, verbose_name='رنگ')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'دسته مشتری',
                'verbose_name_plural': 'دسته\u200cهای مشتری',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_code', models.CharField(help_text='کد یکتای مشتری', max_length=20, unique=True, verbose_name='کد مشتری')),
                ('customer_type', models.CharField(choices=[('individual', 'حقیقی'), ('legal', 'حقوقی')], default='individual', max_length=10, verbose_name='نوع مشتری')),
                ('status', models.CharField(choices=[('active', 'فعال'), ('inactive', 'غیرفعال'), ('suspended', 'معلق')], default='active', max_length=10, verbose_name='وضعیت')),
                ('first_name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('company_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='نام شرکت')),
                ('phone_number', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='شماره تلفن باید در فرمت صحیح وارد شود.', regex='^\\+?1?\\d{9,15}$')], verbose_name='شماره تلفن')),
                ('mobile_number', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message='شماره تلفن باید در فرمت صحیح وارد شود.', regex='^\\+?1?\\d{9,15}$')], verbose_name='شماره موبایل')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('website', models.URLField(blank=True, null=True, verbose_name='وب\u200cسایت')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('postal_code', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'کد پستی باید 10 رقم باشد')], verbose_name='کد پستی')),
                ('city', models.CharField(max_length=100, verbose_name='شهر')),
                ('state', models.CharField(max_length=100, verbose_name='استان')),
                ('country', models.CharField(default='ایران', max_length=100, verbose_name='کشور')),
                ('economic_code', models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.RegexValidator('^\\d{12}$', 'کد اقتصادی باید 12 رقم باشد')], verbose_name='کد اقتصادی')),
                ('national_id', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'شناسه ملی باید 10 رقم باشد')], verbose_name='شناسه ملی')),
                ('registration_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره ثبت')),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='حد اعتبار')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='درصد تخفیف')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='یادداشت\u200cها')),
                ('tags', models.CharField(blank=True, help_text='تگ\u200cها را با کاما جدا کنید', max_length=500, null=True, verbose_name='تگ\u200cها')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط')),
            ],
            options={
                'verbose_name': 'مشتری',
                'verbose_name_plural': 'مشتریان',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerCategoryMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ انتساب')),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='انتساب شده توسط')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customercategory', verbose_name='دسته')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_memberships', to='customers.customer', verbose_name='مشتری')),
            ],
            options={
                'verbose_name': 'عضویت در دسته',
                'verbose_name_plural': 'عضویت\u200cهای دسته',
            },
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['customer_code'], name='customers_c_custome_116ac0_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['phone_number'], name='customers_c_phone_n_cabfe1_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['email'], name='customers_c_email_4fdeb3_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['status'], name='customers_c_status_ce44cf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='customercategorymembership',
            unique_together={('customer', 'category')},
        ),
    ]
