# Generated by Django 5.2.6 on 2025-09-05 21:28

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام انبار')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='کد انبار')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='تلفن')),
                ('manager', models.CharField(blank=True, max_length=100, null=True, verbose_name='مدیر انبار')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='یادداشت\u200cها')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'انبار',
                'verbose_name_plural': 'انبارها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LotNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_number', models.CharField(max_length=50, unique=True, verbose_name='شماره لات')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='مقدار')),
                ('production_date', models.DateField(verbose_name='تاریخ تولید')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='تاریخ انقضا')),
                ('supplier', models.CharField(blank=True, max_length=200, null=True, verbose_name='تأمین\u200cکننده')),
                ('batch_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره بچ')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='یادداشت\u200cها')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='products.product', verbose_name='محصول')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse', verbose_name='انبار')),
            ],
            options={
                'verbose_name': 'شماره لات',
                'verbose_name_plural': 'شماره\u200cهای لات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_type', models.CharField(choices=[('physical_count', 'شمارش فیزیکی'), ('damage', 'آسیب'), ('theft', 'سرقت'), ('expired', 'منقضی شده'), ('other', 'سایر')], max_length=15, verbose_name='نوع تعدیل')),
                ('reference_number', models.CharField(max_length=50, unique=True, verbose_name='شماره مرجع')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='یادداشت\u200cها')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('pending', 'در انتظار تأیید'), ('approved', 'تأیید شده'), ('rejected', 'رد شده')], default='draft', max_length=15, verbose_name='وضعیت')),
                ('adjustment_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ تعدیل')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تأیید')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_adjustments', to=settings.AUTH_USER_MODEL, verbose_name='تأیید شده توسط')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='inventory.warehouse', verbose_name='انبار')),
            ],
            options={
                'verbose_name': 'تعدیل موجودی',
                'verbose_name_plural': 'تعدیل\u200cهای موجودی',
                'ordering': ['-adjustment_date'],
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='مقدار')),
                ('reserved_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='مقدار رزرو شده')),
                ('min_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='حداقل موجودی')),
                ('max_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='حداکثر موجودی')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='مکان در انبار')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='products.product', verbose_name='محصول')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='inventory.warehouse', verbose_name='انبار')),
            ],
            options={
                'verbose_name': 'آیتم موجودی',
                'verbose_name_plural': 'آیتم\u200cهای موجودی',
                'ordering': ['warehouse', 'product'],
            },
        ),
        migrations.CreateModel(
            name='StockAdjustmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مقدار فعلی')),
                ('actual_quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مقدار واقعی')),
                ('difference', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='تفاوت')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='هزینه واحد')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='یادداشت\u200cها')),
                ('adjustment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.stockadjustment', verbose_name='تعدیل')),
                ('lot_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.lotnumber', verbose_name='شماره لات')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'آیتم تعدیل',
                'verbose_name_plural': 'آیتم\u200cهای تعدیل',
                'unique_together': {('adjustment', 'product', 'lot_number')},
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('in', 'ورود'), ('out', 'خروج'), ('transfer', 'انتقال'), ('adjustment', 'تعدیل'), ('reserve', 'رزرو'), ('unreserve', 'لغو رزرو')], max_length=15, verbose_name='نوع حرکت')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مقدار')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='هزینه واحد')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='هزینه کل')),
                ('reference_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='نوع مرجع')),
                ('reference_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='شناسه مرجع')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='یادداشت\u200cها')),
                ('movement_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ حرکت')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط')),
                ('lot_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.lotnumber', verbose_name='شماره لات')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='products.product', verbose_name='محصول')),
                ('destination_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_transfers', to='inventory.warehouse', verbose_name='انبار مقصد')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='inventory.warehouse', verbose_name='انبار')),
            ],
            options={
                'verbose_name': 'حرکت موجودی',
                'verbose_name_plural': 'حرکت\u200cهای موجودی',
                'ordering': ['-movement_date'],
                'indexes': [models.Index(fields=['product'], name='inventory_s_product_cbdc37_idx'), models.Index(fields=['warehouse'], name='inventory_s_warehou_a81054_idx'), models.Index(fields=['movement_type'], name='inventory_s_movemen_018f99_idx'), models.Index(fields=['movement_date'], name='inventory_s_movemen_25c7cf_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='lotnumber',
            index=models.Index(fields=['lot_number'], name='inventory_l_lot_num_663d15_idx'),
        ),
        migrations.AddIndex(
            model_name='lotnumber',
            index=models.Index(fields=['product'], name='inventory_l_product_cfcf83_idx'),
        ),
        migrations.AddIndex(
            model_name='lotnumber',
            index=models.Index(fields=['expiry_date'], name='inventory_l_expiry__47e721_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inventoryitem',
            unique_together={('product', 'warehouse')},
        ),
    ]
