# Generated by Django 5.2.6 on 2025-09-05 21:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام ویژگی')),
                ('attribute_type', models.CharField(choices=[('text', 'متن'), ('number', 'عدد'), ('boolean', 'بله/خیر'), ('choice', 'انتخابی'), ('date', 'تاریخ')], default='text', max_length=10, verbose_name='نوع ویژگی')),
                ('is_required', models.BooleanField(default=False, verbose_name='اجباری')),
                ('is_filterable', models.BooleanField(default=False, verbose_name='قابل فیلتر')),
                ('choices', models.TextField(blank=True, help_text='برای نوع انتخابی، گزینه\u200cها را در هر خط بنویسید', null=True, verbose_name='گزینه\u200cها')),
                ('unit', models.CharField(blank=True, max_length=20, null=True, verbose_name='واحد')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
            ],
            options={
                'verbose_name': 'ویژگی محصول',
                'verbose_name_plural': 'ویژگی\u200cهای محصول',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام دسته')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_categories/', verbose_name='تصویر')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.productcategory', verbose_name='دسته والد')),
            ],
            options={
                'verbose_name': 'دسته محصول',
                'verbose_name_plural': 'دسته\u200cهای محصول',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=50, unique=True, verbose_name='کد محصول')),
                ('barcode', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='بارکد')),
                ('name', models.CharField(max_length=200, verbose_name='نام محصول')),
                ('name_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='نام انگلیسی')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('short_description', models.CharField(blank=True, max_length=500, null=True, verbose_name='توضیحات کوتاه')),
                ('base_unit', models.CharField(choices=[('piece', 'عدد'), ('kg', 'کیلوگرم'), ('gram', 'گرم'), ('liter', 'لیتر'), ('meter', 'متر'), ('box', 'جعبه'), ('pack', 'بسته'), ('set', 'ست'), ('other', 'سایر')], default='piece', max_length=10, verbose_name='واحد پایه')),
                ('purchase_unit', models.CharField(choices=[('piece', 'عدد'), ('kg', 'کیلوگرم'), ('gram', 'گرم'), ('liter', 'لیتر'), ('meter', 'متر'), ('box', 'جعبه'), ('pack', 'بسته'), ('set', 'ست'), ('other', 'سایر')], default='piece', max_length=10, verbose_name='واحد خرید')),
                ('sale_unit', models.CharField(choices=[('piece', 'عدد'), ('kg', 'کیلوگرم'), ('gram', 'گرم'), ('liter', 'لیتر'), ('meter', 'متر'), ('box', 'جعبه'), ('pack', 'بسته'), ('set', 'ست'), ('other', 'سایر')], default='piece', max_length=10, verbose_name='واحد فروش')),
                ('purchase_to_base_ratio', models.DecimalField(decimal_places=4, default=1, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='نسبت خرید به پایه')),
                ('sale_to_base_ratio', models.DecimalField(decimal_places=4, default=1, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='نسبت فروش به پایه')),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت تمام شده')),
                ('sale_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت فروش')),
                ('wholesale_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت عمده')),
                ('min_stock', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='حداقل موجودی')),
                ('max_stock', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='حداکثر موجودی')),
                ('current_stock', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='موجودی فعلی')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='نرخ مالیات (%)')),
                ('discount_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='نرخ تخفیف (%)')),
                ('status', models.CharField(choices=[('active', 'فعال'), ('inactive', 'غیرفعال'), ('discontinued', 'متوقف شده'), ('draft', 'پیش\u200cنویس')], default='active', max_length=15, verbose_name='وضعیت')),
                ('is_service', models.BooleanField(default=False, verbose_name='خدمات')),
                ('is_digital', models.BooleanField(default=False, verbose_name='محصول دیجیتال')),
                ('weight', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='وزن (کیلوگرم)')),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='طول (سانتی\u200cمتر)')),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='عرض (سانتی\u200cمتر)')),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='ارتفاع (سانتی\u200cمتر)')),
                ('tags', models.CharField(blank=True, help_text='تگ\u200cها را با کاما جدا کنید', max_length=500, null=True, verbose_name='تگ\u200cها')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='یادداشت\u200cها')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.productcategory', verbose_name='دسته')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images/', verbose_name='تصویر')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='عنوان')),
                ('alt_text', models.CharField(blank=True, max_length=200, null=True, verbose_name='متن جایگزین')),
                ('is_primary', models.BooleanField(default=False, verbose_name='تصویر اصلی')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'تصویر محصول',
                'verbose_name_plural': 'تصاویر محصول',
                'ordering': ['product', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ProductAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_text', models.TextField(blank=True, null=True, verbose_name='مقدار متنی')),
                ('value_number', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='مقدار عددی')),
                ('value_boolean', models.BooleanField(blank=True, null=True, verbose_name='مقدار بولی')),
                ('value_date', models.DateField(blank=True, null=True, verbose_name='مقدار تاریخ')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productattribute', verbose_name='ویژگی')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='products.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'مقدار ویژگی',
                'verbose_name_plural': 'مقادیر ویژگی\u200cها',
                'unique_together': {('product', 'attribute')},
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['product_code'], name='products_pr_product_e20ae7_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['barcode'], name='products_pr_barcode_e44f4f_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='products_pr_name_9ff0a3_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='products_pr_categor_9edb3d_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status'], name='products_pr_status_041708_idx'),
        ),
    ]
