# Generated by Django 5.2.6 on 2025-09-05 21:28

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxPayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxpayer_id', models.CharField(max_length=20, unique=True, verbose_name='شناسه مودی')),
                ('taxpayer_type', models.CharField(choices=[('individual', 'حقیقی'), ('legal', 'حقوقی')], max_length=10, verbose_name='نوع مودی')),
                ('status', models.CharField(choices=[('active', 'فعال'), ('inactive', 'غیرفعال'), ('suspended', 'معلق'), ('blacklisted', 'لیست سیاه')], default='active', max_length=15, verbose_name='وضعیت')),
                ('tax_office_code', models.CharField(max_length=10, verbose_name='کد اداره مالیات')),
                ('tax_office_name', models.CharField(max_length=200, verbose_name='نام اداره مالیات')),
                ('economic_code', models.CharField(max_length=12, unique=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='کد اقتصادی')),
                ('national_id', models.CharField(max_length=10, unique=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='شناسه ملی')),
                ('registration_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره ثبت')),
                ('annual_turnover', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='گردش مالی سالانه')),
                ('tax_exempt', models.BooleanField(default=False, verbose_name='معاف از مالیات')),
                ('tax_exemption_reason', models.TextField(blank=True, null=True, verbose_name='دلیل معافیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='taxpayer', to='customers.customer', verbose_name='مشتری')),
            ],
            options={
                'verbose_name': 'مودی مالیاتی',
                'verbose_name_plural': 'مودیان مالیاتی',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_type', models.CharField(choices=[('vat', 'مالیات بر ارزش افزوده'), ('income', 'مالیات بر درآمد'), ('corporate', 'مالیات بر درآمد اشخاص حقوقی'), ('withholding', 'مالیات تکلیفی'), ('stamp', 'تمبر'), ('other', 'سایر')], max_length=15, verbose_name='نوع مالیات')),
                ('name', models.CharField(max_length=200, verbose_name='نام نرخ')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='نرخ (درصد)')),
                ('effective_from', models.DateField(verbose_name='اعتبار از تاریخ')),
                ('effective_to', models.DateField(blank=True, null=True, verbose_name='اعتبار تا تاریخ')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'نرخ مالیاتی',
                'verbose_name_plural': 'نرخ\u200cهای مالیاتی',
                'ordering': ['-effective_from', 'tax_type'],
                'indexes': [models.Index(fields=['tax_type'], name='tax_system__tax_typ_5078ed_idx'), models.Index(fields=['effective_from'], name='tax_system__effecti_7e71b7_idx'), models.Index(fields=['is_active'], name='tax_system__is_acti_af3034_idx')],
            },
        ),
        migrations.CreateModel(
            name='TaxTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_number', models.CharField(max_length=50, unique=True, verbose_name='شماره تراکنش')),
                ('transaction_type', models.CharField(choices=[('sale', 'فروش'), ('purchase', 'خرید'), ('return', 'مرجوعی'), ('adjustment', 'تعدیل'), ('exemption', 'معافیت')], max_length=15, verbose_name='نوع تراکنش')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('submitted', 'ارسال شده'), ('accepted', 'پذیرفته شده'), ('rejected', 'رد شده'), ('cancelled', 'لغو شده')], default='draft', max_length=15, verbose_name='وضعیت')),
                ('reference_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='نوع مرجع')),
                ('reference_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='شناسه مرجع')),
                ('transaction_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ تراکنش')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='تاریخ سررسید')),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='مبلغ ناخالص')),
                ('tax_exempt_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='مبلغ معاف')),
                ('taxable_amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='مبلغ مشمول مالیات')),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='مبلغ مالیات')),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='مبلغ خالص')),
                ('description', models.TextField(blank=True, null=True, verbose_name='شرح')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='یادداشت\u200cها')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط')),
                ('taxpayer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_transactions', to='tax_system.taxpayer', verbose_name='مودی')),
            ],
            options={
                'verbose_name': 'تراکنش مالیاتی',
                'verbose_name_plural': 'تراکنش\u200cهای مالیاتی',
                'ordering': ['-transaction_date'],
            },
        ),
        migrations.AddIndex(
            model_name='taxpayer',
            index=models.Index(fields=['taxpayer_id'], name='tax_system__taxpaye_a320c8_idx'),
        ),
        migrations.AddIndex(
            model_name='taxpayer',
            index=models.Index(fields=['economic_code'], name='tax_system__economi_3e4147_idx'),
        ),
        migrations.AddIndex(
            model_name='taxpayer',
            index=models.Index(fields=['national_id'], name='tax_system__nationa_ec5565_idx'),
        ),
        migrations.AddIndex(
            model_name='taxpayer',
            index=models.Index(fields=['status'], name='tax_system__status_fbf74e_idx'),
        ),
        migrations.AddIndex(
            model_name='taxtransaction',
            index=models.Index(fields=['transaction_number'], name='tax_system__transac_562fa4_idx'),
        ),
        migrations.AddIndex(
            model_name='taxtransaction',
            index=models.Index(fields=['taxpayer'], name='tax_system__taxpaye_a042c9_idx'),
        ),
        migrations.AddIndex(
            model_name='taxtransaction',
            index=models.Index(fields=['transaction_type'], name='tax_system__transac_a2e024_idx'),
        ),
        migrations.AddIndex(
            model_name='taxtransaction',
            index=models.Index(fields=['status'], name='tax_system__status_87e429_idx'),
        ),
        migrations.AddIndex(
            model_name='taxtransaction',
            index=models.Index(fields=['transaction_date'], name='tax_system__transac_7cb838_idx'),
        ),
    ]
