# Generated by Django 5.2.6 on 2025-09-05 21:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام داشبورد')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('is_public', models.BooleanField(default=False, verbose_name='عمومی')),
                ('is_default', models.BooleanField(default=False, verbose_name='پیش\u200cفرض')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_dashboards', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط')),
            ],
            options={
                'verbose_name': 'داشبورد',
                'verbose_name_plural': 'داشبوردها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('widget_type', models.CharField(choices=[('chart', 'نمودار'), ('table', 'جدول'), ('metric', 'معیار'), ('gauge', 'سنج'), ('map', 'نقشه'), ('text', 'متن')], max_length=10, verbose_name='نوع ویجت')),
                ('chart_type', models.CharField(blank=True, choices=[('line', 'خطی'), ('bar', 'ستونی'), ('pie', 'دایره\u200cای'), ('area', 'ناحیه\u200cای'), ('scatter', 'پراکندگی'), ('donut', 'دونات')], max_length=10, null=True, verbose_name='نوع نمودار')),
                ('data_source', models.CharField(max_length=200, verbose_name='منبع داده')),
                ('query', models.TextField(verbose_name='کوئری')),
                ('position_x', models.PositiveIntegerField(default=0, verbose_name='موقعیت X')),
                ('position_y', models.PositiveIntegerField(default=0, verbose_name='موقعیت Y')),
                ('width', models.PositiveIntegerField(default=4, verbose_name='عرض')),
                ('height', models.PositiveIntegerField(default=3, verbose_name='ارتفاع')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='reports.dashboard', verbose_name='داشبورد')),
            ],
            options={
                'verbose_name': 'ویجت داشبورد',
                'verbose_name_plural': 'ویجت\u200cهای داشبورد',
                'ordering': ['dashboard', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ReportSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام زمان\u200cبندی')),
                ('frequency', models.CharField(choices=[('daily', 'روزانه'), ('weekly', 'هفتگی'), ('monthly', 'ماهانه'), ('quarterly', 'فصلانه'), ('yearly', 'سالانه'), ('custom', 'سفارشی')], max_length=15, verbose_name='فرکانس')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('next_run', models.DateTimeField(verbose_name='اجرای بعدی')),
                ('last_run', models.DateTimeField(blank=True, null=True, verbose_name='آخرین اجرا')),
                ('email_recipients', models.TextField(blank=True, help_text='ایمیل\u200cها را با کاما جدا کنید', null=True, verbose_name='گیرندگان ایمیل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط')),
            ],
            options={
                'verbose_name': 'زمان\u200cبندی گزارش',
                'verbose_name_plural': 'زمان\u200cبندی گزارش\u200cها',
                'ordering': ['next_run'],
            },
        ),
        migrations.CreateModel(
            name='ReportExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('running', 'در حال اجرا'), ('completed', 'تکمیل شده'), ('failed', 'ناموفق'), ('cancelled', 'لغو شده')], default='pending', max_length=15, verbose_name='وضعیت')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='شروع شده در')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تکمیل شده در')),
                ('file_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='مسیر فایل')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='پیام خطا')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='reports.reportschedule', verbose_name='زمان\u200cبندی')),
            ],
            options={
                'verbose_name': 'اجرای گزارش',
                'verbose_name_plural': 'اجراهای گزارش',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام قالب')),
                ('report_type', models.CharField(choices=[('financial', 'مالی'), ('sales', 'فروش'), ('inventory', 'انبار'), ('customer', 'مشتری'), ('tax', 'مالیاتی'), ('custom', 'سفارشی')], max_length=15, verbose_name='نوع گزارش')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('template_file', models.FileField(upload_to='report_templates/', verbose_name='فایل قالب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط')),
            ],
            options={
                'verbose_name': 'قالب گزارش',
                'verbose_name_plural': 'قالب\u200cهای گزارش',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='reportschedule',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='reports.reporttemplate', verbose_name='قالب گزارش'),
        ),
    ]
