# Generated by Django 5.2.6 on 2025-09-05 21:28

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('personnel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_name', models.CharField(max_length=200, verbose_name='نام فرایند')),
                ('process_type', models.CharField(choices=[('lead', 'سرنخ'), ('opportunity', 'فرصت'), ('proposal', 'پیشنهاد'), ('negotiation', 'مذاکره'), ('closed_won', 'بسته شده - موفق'), ('closed_lost', 'بسته شده - ناموفق')], max_length=15, verbose_name='نوع فرایند')),
                ('priority', models.CharField(choices=[('low', 'پایین'), ('medium', 'متوسط'), ('high', 'بالا'), ('urgent', 'فوری')], default='medium', max_length=10, verbose_name='اولویت')),
                ('estimated_value', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='ارزش تخمینی')),
                ('actual_value', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='ارزش واقعی')),
                ('probability', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MinValueValidator(100)], verbose_name='احتمال موفقیت (%)')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ شروع')),
                ('expected_close_date', models.DateField(blank=True, null=True, verbose_name='تاریخ بسته شدن مورد انتظار')),
                ('actual_close_date', models.DateField(blank=True, null=True, verbose_name='تاریخ بسته شدن واقعی')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='یادداشت\u200cها')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_processes', to=settings.AUTH_USER_MODEL, verbose_name='واگذار شده به')),
                ('contact_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='personnel.personnel', verbose_name='شخص تماس')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_processes', to='customers.customer', verbose_name='مشتری')),
            ],
            options={
                'verbose_name': 'فرایند فروش',
                'verbose_name_plural': 'فرایندهای فروش',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_name', models.CharField(max_length=200, verbose_name='نام مرحله')),
                ('stage_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب مرحله')),
                ('is_completed', models.BooleanField(default=False, verbose_name='تکمیل شده')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تکمیل')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='یادداشت\u200cها')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تکمیل شده توسط')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='crm.salesprocess', verbose_name='فرایند')),
            ],
            options={
                'verbose_name': 'مرحله فرایند',
                'verbose_name_plural': 'مراحل فرایند',
                'ordering': ['process', 'stage_order'],
            },
        ),
        migrations.CreateModel(
            name='ProcessActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('call', 'تماس تلفنی'), ('email', 'ایمیل'), ('meeting', 'جلسه'), ('visit', 'بازدید'), ('proposal', 'ارسال پیشنهاد'), ('follow_up', 'پیگیری'), ('other', 'سایر')], max_length=15, verbose_name='نوع فعالیت')),
                ('subject', models.CharField(max_length=200, verbose_name='موضوع')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('activity_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ فعالیت')),
                ('duration', models.PositiveIntegerField(blank=True, help_text='مدت زمان به دقیقه', null=True, verbose_name='مدت زمان')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crm.salesprocess', verbose_name='فرایند')),
            ],
            options={
                'verbose_name': 'فعالیت فرایند',
                'verbose_name_plural': 'فعالیت\u200cهای فرایند',
                'ordering': ['-activity_date'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('priority', models.CharField(choices=[('low', 'پایین'), ('medium', 'متوسط'), ('high', 'بالا'), ('urgent', 'فوری')], default='medium', max_length=10, verbose_name='اولویت')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('in_progress', 'در حال انجام'), ('completed', 'تکمیل شده'), ('cancelled', 'لغو شده')], default='pending', max_length=15, verbose_name='وضعیت')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ سررسید')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تکمیل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('reference_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='نوع مرجع')),
                ('reference_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='شناسه مرجع')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='واگذار شده به')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط')),
            ],
            options={
                'verbose_name': 'وظیفه',
                'verbose_name_plural': 'وظایف',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_name', models.CharField(max_length=200, verbose_name='نام سرنخ')),
                ('company_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='نام شرکت')),
                ('contact_person', models.CharField(blank=True, max_length=200, null=True, verbose_name='شخص تماس')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='تلفن')),
                ('source', models.CharField(choices=[('website', 'وب\u200cسایت'), ('referral', 'معرفی'), ('advertisement', 'تبلیغات'), ('cold_call', 'تماس سرد'), ('email', 'ایمیل'), ('social_media', 'شبکه\u200cهای اجتماعی'), ('event', 'رویداد'), ('other', 'سایر')], max_length=15, verbose_name='منبع')),
                ('status', models.CharField(choices=[('new', 'جدید'), ('contacted', 'تماس گرفته شده'), ('qualified', 'صلاحیت\u200cدار'), ('unqualified', 'غیرصلاحیت\u200cدار'), ('converted', 'تبدیل شده'), ('lost', 'از دست رفته')], default='new', max_length=15, verbose_name='وضعیت')),
                ('industry', models.CharField(blank=True, max_length=100, null=True, verbose_name='صنعت')),
                ('company_size', models.CharField(blank=True, max_length=50, null=True, verbose_name='اندازه شرکت')),
                ('estimated_value', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='ارزش تخمینی')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='یادداشت\u200cها')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('converted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تبدیل')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL, verbose_name='واگذار شده به')),
                ('converted_to_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_from_lead', to='customers.customer', verbose_name='تبدیل شده به مشتری')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط')),
            ],
            options={
                'verbose_name': 'سرنخ',
                'verbose_name_plural': 'سرنخ\u200cها',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='crm_lead_status_2c1bc7_idx'), models.Index(fields=['source'], name='crm_lead_source_0cf4cf_idx'), models.Index(fields=['assigned_to'], name='crm_lead_assigne_2d9eb1_idx'), models.Index(fields=['created_at'], name='crm_lead_created_d9bbc3_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='salesprocess',
            index=models.Index(fields=['customer'], name='crm_salespr_custome_bb8f79_idx'),
        ),
        migrations.AddIndex(
            model_name='salesprocess',
            index=models.Index(fields=['process_type'], name='crm_salespr_process_32919c_idx'),
        ),
        migrations.AddIndex(
            model_name='salesprocess',
            index=models.Index(fields=['priority'], name='crm_salespr_priorit_4800cb_idx'),
        ),
        migrations.AddIndex(
            model_name='salesprocess',
            index=models.Index(fields=['assigned_to'], name='crm_salespr_assigne_fa38a7_idx'),
        ),
        migrations.AddIndex(
            model_name='salesprocess',
            index=models.Index(fields=['start_date'], name='crm_salespr_start_d_2711d4_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status'], name='crm_task_status_cb3ea6_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['priority'], name='crm_task_priorit_c2402e_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['assigned_to'], name='crm_task_assigne_78425b_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['due_date'], name='crm_task_due_dat_0218a5_idx'),
        ),
    ]
