# Generated by Django 5.2.6 on 2025-09-05 21:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('father_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام پدر')),
                ('national_id', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'کد ملی باید 10 رقم باشد')], verbose_name='کد ملی')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('gender', models.CharField(blank=True, choices=[('male', 'مرد'), ('female', 'زن')], max_length=6, null=True, verbose_name='جنسیت')),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'مجرد'), ('married', 'متأهل'), ('divorced', 'مطلقه'), ('widowed', 'بیوه')], max_length=10, null=True, verbose_name='وضعیت تأهل')),
                ('phone_number', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message='شماره تلفن باید در فرمت صحیح وارد شود.', regex='^\\+?1?\\d{9,15}$')], verbose_name='شماره تلفن')),
                ('mobile_number', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='شماره تلفن باید در فرمت صحیح وارد شود.', regex='^\\+?1?\\d{9,15}$')], verbose_name='شماره موبایل')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس')),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'کد پستی باید 10 رقم باشد')], verbose_name='کد پستی')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='شهر')),
                ('position', models.CharField(max_length=100, verbose_name='سمت')),
                ('department', models.CharField(blank=True, max_length=100, null=True, verbose_name='بخش')),
                ('employee_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره پرسنلی')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='تاریخ استخدام')),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='حقوق')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='یادداشت\u200cها')),
                ('is_primary_contact', models.BooleanField(default=False, help_text='آیا این شخص تماس اصلی مشتری است؟', verbose_name='تماس اصلی')),
                ('is_authorized_for_orders', models.BooleanField(default=False, help_text='آیا این شخص مجاز به ثبت سفارش است؟', verbose_name='مجاز برای سفارش')),
                ('is_authorized_for_payment', models.BooleanField(default=False, help_text='آیا این شخص مجاز به تأیید پرداخت است؟', verbose_name='مجاز برای پرداخت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personnel', to='customers.customer', verbose_name='مشتری')),
            ],
            options={
                'verbose_name': 'پرسنل',
                'verbose_name_plural': 'پرسنل',
                'ordering': ['customer', 'last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='PersonnelContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(choices=[('phone', 'تلفن'), ('mobile', 'موبایل'), ('email', 'ایمیل'), ('fax', 'فکس'), ('whatsapp', 'واتساپ'), ('telegram', 'تلگرام'), ('other', 'سایر')], max_length=10, verbose_name='نوع تماس')),
                ('value', models.CharField(max_length=200, verbose_name='مقدار')),
                ('is_primary', models.BooleanField(default=False, verbose_name='اصلی')),
                ('notes', models.CharField(blank=True, max_length=200, null=True, verbose_name='یادداشت')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='personnel.personnel', verbose_name='پرسنل')),
            ],
            options={
                'verbose_name': 'تماس پرسنل',
                'verbose_name_plural': 'تماس\u200cهای پرسنل',
                'ordering': ['personnel', 'contact_type'],
            },
        ),
        migrations.CreateModel(
            name='PersonnelDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('id_card', 'کارت ملی'), ('birth_certificate', 'شناسنامه'), ('passport', 'پاسپورت'), ('contract', 'قرارداد'), ('other', 'سایر')], max_length=20, verbose_name='نوع سند')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان سند')),
                ('file', models.FileField(upload_to='personnel_documents/', verbose_name='فایل')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ آپلود')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='personnel.personnel', verbose_name='پرسنل')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='آپلود شده توسط')),
            ],
            options={
                'verbose_name': 'سند پرسنل',
                'verbose_name_plural': 'اسناد پرسنل',
                'ordering': ['-upload_date'],
            },
        ),
        migrations.AddIndex(
            model_name='personnel',
            index=models.Index(fields=['customer'], name='personnel_p_custome_e2f802_idx'),
        ),
        migrations.AddIndex(
            model_name='personnel',
            index=models.Index(fields=['national_id'], name='personnel_p_nationa_01fbed_idx'),
        ),
        migrations.AddIndex(
            model_name='personnel',
            index=models.Index(fields=['mobile_number'], name='personnel_p_mobile__596564_idx'),
        ),
        migrations.AddIndex(
            model_name='personnel',
            index=models.Index(fields=['position'], name='personnel_p_positio_2b1839_idx'),
        ),
    ]
